# Generated by Django 4.2.6 on 2023-10-07 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transport_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="Comapines",
        ),
    ]
