# Generated by Django 4.2.6 on 2023-10-07 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transport_api", "0002_alter_company_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="companies",
        ),
    ]
