# Generated by Django 4.2.6 on 2023-10-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transport_api", "0004_alter_company_trucks"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport_api.company",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport_api.truck",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="company",
            name="trucks"
        ),
        migrations.AddField(
            model_name="company",
            name="trucks",
            field=models.ManyToManyField(
                blank=True,
                through="transport_api.CompanyTruck",
                to="transport_api.truck",
            ),
        ),
    ]
